version: '3.8'

networks:
  # Specify the network for bridging
  l0k_swap-network:
    driver: bridge

services:
  backend:
    build: ./backend
    command: yarn run start
    environment:
      NODE_ENV: 'development'
      PROMETHEUS_ALERTMANAGER: '{"api":"http://alertmanager:9093"}' # {"api":"http://alertmanager:9093"}
      DB_HOST: db
      DB_PORT: '${DB_PORT}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      APP_OPTIONS_PORT: '${APP_OPTIONS_PORT}'
      APP_OPTIONS_HOST: '${APP_OPTIONS_HOST}'
      FAUCET_PRIVATE_KEY: '${FAUCET_PRIVATE_KEY}'
    volumes:
      - './backend/logs:/app/logs'
    #   - './backend:/app'
    ports:
      - '3000:3000'
    restart: always
    networks:
      - l0k_swap-network

  twitter-crawl:
    build: ./twitter-crawl
    command: ./twitter-crawl
    environment:
      DB_HOST: db
      DB_PORT: '${DB_PORT}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      TWEET_QUERY: '10Kswap'
      PRODUCT_ENV: 'develop'
    restart: always
    networks:
      - l0k_swap-network

  db:
    image: mysql:5.7.16
    # image: ibex/debian-mysql-server-5.7
    # Set mysqld charset
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_TCP_PORT: '${DB_PORT}'
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/conf.d:/etc/mysql/conf.d'
    ports:
      - '3308:3308'
    restart: always
    networks:
      - l0k_swap-network

  nginx:
    image: nginx:alpine
    volumes:
      - './nginx.default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/log:/var/log/nginx'
      - './nginx.domain.crt:/etc/nginx/certs/domain.crt'
      - './nginx.domain.key:/etc/nginx/certs/domain.key'
    ports:
      - '80:80'
      - '443:443'
    restart: always
    networks:
      - l0k_swap-network
